- name: Install minikube
  hosts: "{{ host }}"
  vars_files: 
    - vars/vars.yml


  tasks:

  - name: Install k3s
    include_tasks: "playbooks/k3s.yml"

  - name: install prerequisites
    become: yes
    ansible.builtin.apt:
      pkg:
        - ca-certificates
        - curl
        - make
        - git



  - block: 

      - name: Check latest version
        uri:
          url: "{{ awx_githubapi_url }}"
          return_content: true
        register: awx_latest

      - name: Define version to checkout
        set_fact: checkout_version="{{ awx_latest.json.tag_name }}"

          
        when: awx_operator_version == 'latest'

      - name: Print latest checkout_version variable
        debug:
          msg: "{{ checkout_version }}" 

  - name: Git checkout
    ansible.builtin.git:
      repo: '{{ awx_operator_git_link }}'
      dest: "{{ awx_operator_git_name }}/"
      version: "{{ checkout_version }}"
      force: yes

  - name: Git checkout
    ansible.builtin.git:
      repo: '{{ awx_git_helper_url }}'
      dest: "{{ awx_git_helper_dir }}/"
      version: "{{ awx_git_helper_version }}"
      force: yes  

  # - name: Make AWX operator deploy
  #   ansible.builtin.command: make deploy
  #   args:
  #     chdir: "{{ awx_operator_git_name }}/"
  #   environment:
  #        NAMESPACE: "{{ NAMESPACE }}"

  # - name: Waiting for Operator to start
  #   shell: kubectl get pods -o json --namespace=awx --selector control-plane=controller-manager
  #   register: kubectl_get_pods
  #   until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  #   retries: 3
  #   delay: 90


  - name: Make self-signed certificate
    ansible.builtin.command: openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -out ./base/tls.crt -keyout ./base/tls.key -subj "/CN=${{AWX_HOST}}/O=${{AWX_HOST}}" -addext "subjectAltName = DNS:${{AWX_HOST}}"
    args:
      chdir: "{{ awx_git_helper_dir }}/"
    environment:
         NAMESPACE: "{{ NAMESPACE }}"



  