- name: Get password for AWX install
  hosts: "{{ host }}"
  vars_files: 
    - vars/vars.yml

  tasks:
  


  - name: Get user admin password
    shell: kubectl get secret ansible-awx-admin-password --namespace=ansible-awx -o jsonpath="{.data.password}" | base64 --decode; echo
    register: admin_password

  - name: Print admin password
    debug: 
      msg: "Login with username: admin and password: {{admin_password.stdout}} using url http://127.0.0.1:10445"
      

  