- name: Get password for AWX install
  hosts: "{{ host }}"
  vars_files: 
    - vars/vars.yml

  tasks:
  


  - name: Get user admin password
    shell: kubectl get secret ansible-awx-admin-password -o jsonpath="{.data.password}" | base64 --decode; echo
    register: admin_password



  