- name: Install minikube
  hosts: "{{ host }}"
  vars_files: 
    - vars/vars.yml

  roles:
    - role:  gantsign.minikube

  tasks:

  - name: Start minikube instance
    register: minikube_info
    shell: |
      minikube start --install-addons=true
      minikube status
    
  - name: Git checkout
    ansible.builtin.git:
      repo: '{{ awx_operator_git_link }}'
      dest: "{{ pathfinder_git_name }}/"
      version: "{{ awx_version }}"

  - name: "Making deploy for AWX"
    ansible.builtin.command: make deploy
    args:
      chdir: "{{ pathfinder_git_name }}"
    environment:
         NAMESPACE: "{{ namespace }}"

  - name: "Cluster current status"
    ansible.builtin.command:  kubectl get pods -n "{{ namespace }}"

      
    