- name: Install docker stuff
  hosts: "{{ host }}"

  -roles:

    - role: gantsign.antigen
      users:
        - username: vagrant
          antigen_libraries:
            - name: oh-my-zsh
          antigen_bundles:
            # Oh My Zsh Minikube plugin
            - name: minikube

  