- name: Install minikube
  hosts: "{{ host }}"

  roles:
    - role:  gantsign.minikube

    # - role: gantsign.antigen
    #   users:
    #     - username: vagrant
    #       antigen_libraries:
    #         - name: oh-my-zsh
    #       antigen_bundles:
    #         # Oh My Zsh Minikube plugin
    #         - name: minikube

  