- name: Install minikube
  hosts: "{{ host }}"
  vars_files: 
    - vars/vars.yml

  roles:
    - role:  gantsign.minikube

  tasks:
  
  - name: install make
    become: yes
    ansible.builtin.apt:
      pkg:
        - make

  - name: Install kubectl
    become: yes
    shell: 
      cmd: snap install kubectl --classic


  - name: Add Anisble user to the docker group
    ansible.builtin.user:
      name: "{{ ansible_user }}"
      groups: "{{ docker_group }}"
      append: yes

    

  # - name: Start minikube instance
  #   register: minikube_info
  #   shell: |
  #     minikube start --install-addons=true
  #     minikube status
    
  - name: Git checkout
    ansible.builtin.git:
      repo: '{{ awx_operator_git_link }}'
      dest: "{{ awx_operator_git_name }}/"
      version: "{{ awx_operator_version }}"
      force: yes

  # - name: "Making deploy for AWX"
  #   ansible.builtin.command: make deploy
  #   args:
  #     chdir: "{{ awx_operator_git_name }}/"
  #   environment:
  #        NAMESPACE: "{{ namespace }}"

  - name: Rename file 
    ansible.builtin.copy:
      remote_src: true
      src: "{{ awx_operator_git_name }}/{{ awx_demo_config_file }}"
      dest: "{{ awx_operator_git_name }}/{{ awx_config_file }}"

  - name: "Change configuration for {{awx_config_file}}"
    replace:
      path: "{{ awx_operator_git_name }}/{{awx_config_file}}"
      regexp: '(^name:\s)(.*)$'
      replace: "name: {{ namespace }}"


      
    