- name: Install minikube
  hosts: "{{ host }}"

  roles:
    - role:  gantsign.minikube

  tasks:

  - name: Start minikube instance
    register: minikube_info
    shell: |
      minikube delete
      minikube start --install-addons=true
      minikube status
      minikube cluster-info
    



    # - role: gantsign.antigen
    #   users:
    #     - username: vagrant
    #       antigen_libraries:
    #         - name: oh-my-zsh
    #       antigen_bundles:
    #         # Oh My Zsh Minikube plugin
    #         - name: minikube

  