- name: test
  hosts: "{{ host }}"

  tasks:

  - name: wait for pods to come up
    shell: kubectl get pods --namespace ansible-awx -o json
    register: kubectl_get_pods
    until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
    retries: 12
    delay: 5