- name: test
  hosts: "{{ host }}"

  tasks:

  # - name: wait for pods to come up
  #   shell: kubectl get pods --namespace ansible-awx -o json
  #   register: kubectl_get_pods
  #   until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  #   retries: 2
  #   delay: 2

    - name: Wait till the Object is created
      community.kubernetes.k8s_info:
        kind: Pod
        wait: true
        name: pod-not-yet-created
        namespace: ansible-awx
        wait_sleep: 10
        wait_timeout: 50